version: 0.0
os: linux
files:
  - source: /
    destination: /root/nodejs-service
file_exists_behavior: OVERWRITE
permissions:
  - object: /root/nodejs-service
    pattern: "**"
    mode: 777
    owner: ec2-user
    type:
      - directory
hooks:
  BeforeInstall:
    - location: devOps/scripts/install_dependencies.sh
      timeout: 300
  ApplicationStart:
    - location: devOps/scripts/start_server.sh
      timeout: 300 
  ApplicationStop:
    - location: devOps/scripts/stop_server.sh
      timeout: 300